// ID identifying the cluster to create. Use your username so that resources created can be tracked back to you.
cluster_id = "openshift"

// Domain of the cluster. This should be "${cluster_id}.${base_domain}".
cluster_domain = "openshift.bdlab.local"

// Base domain from which the cluster domain is a subdomain.
base_domain = "bdlab.local"

// Name of the vSphere server. The dev cluster is on "vcsa.vmware.devcluster.openshift.com".
vsphere_server = "10.6.202.13"

// User on the vSphere server.
vsphere_user = "administrator@bdlab.local"

// Password of the user on the vSphere server.
vsphere_password = "******"

// Name of the vSphere cluster. The dev cluster is "devel".
vsphere_cluster = "JX2LESX"

// Name of the vSphere data center. The dev cluster is "dc1".
vsphere_datacenter = "JX2LAB"

// Name of the vSphere data store to use for the VMs. The dev cluster uses "nvme-ds1".
vsphere_datastore = "JX2PSAN02-LESX-VMS-01"

// Name of the VM template to clone to create VMs for the cluster. The dev cluster has a template named "rhcos-latest".
vm_template = "rhcos-4.4.3"

// The machine_cidr where IP addresses will be assigned for cluster nodes.
// Additionally, IPAM will assign IPs based on the network ID. 
machine_cidr = "10.0.0.0/24"

// The number of control plane VMs to create. Default is 3.
control_plane_count = 3

// The number of compute VMs to create. Default is 3.
compute_count = 2

// URL of the bootstrap ignition. This needs to be publicly accessible so that the bootstrap machine can pull the ignition.
bootstrap_ignition_url = "http://10.6.202.68:8080/install/bootstrap.ign"

// Ignition config for the control plane machines. You should copy the contents of the master.ign generated by the installer.
control_plane_ignition = <<END_OF_MASTER_IGNITION
{"ignition":{"config":{"append":[{"source":"https://api-int.openshift.bdlab.local:22623/config/master","verification":{}}]},"security":{"tls":{"certificateAuthorities":[{"source":"data:text/plain;charset=utf-8;base64,LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURFRENDQWZpZ0F3SUJBZ0lJUDRtN1Y3WFJEK2d3RFFZSktvWklodmNOQVFFTEJRQXdKakVTTUJBR0ExVUUKQ3hNSmIzQmxibk5vYVdaME1SQXdEZ1lEVlFRREV3ZHliMjkwTFdOaE1CNFhEVEl3TURVeU56RTVOVE15TWxvWApEVE13TURVeU5URTVOVE15TWxvd0pqRVNNQkFHQTFVRUN4TUpiM0JsYm5Ob2FXWjBNUkF3RGdZRFZRUURFd2R5CmIyOTBMV05oTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF0cFpBUWhoUzFjMVcKZWI2S2ZKS3h5Q1NiZG05eXJuaTAyaFUvMGZLNGo1MGp0MzRib3kvUnRncjVBMU5yRkovYkgrNnFSSmxYM1BLaAorUk4wL0p2cHVYODhxenZCcFpiOXVxQnR3eUtyRENpMWpzWTRIanpSc1ZFdVo0UFdPb0dRT1pucHY0ZG9nUU1xCjNZYzBRb2pieW5ESjhlNTgwcHJFZXd3Zm9IV1FSMVRyVDZaS1E0NFJqNmE4eU9TbzUreldaYnhOWkdqSksyeGMKQkNtUEtVSEpFK2xPbUNFYThMeWJKRHR5VTdMQmFVMm9OU2hIb1NuOG5VeTBFdE1wVldXVGJOblhJYmM3WFR4ZwpjU2o2R2pheWRnWmdjcURveHJneEl3ZGVWczZjQ2dMRkdEMHBKRHZ1YXg1TkpMQU1oZjZJTzJBUDllTTV6ME9iCkt0UlhqZjc2eVFJREFRQUJvMEl3UURBT0JnTlZIUThCQWY4RUJBTUNBcVF3RHdZRFZSMFRBUUgvQkFVd0F3RUIKL3pBZEJnTlZIUTRFRmdRVVhPRlpNYVJjcWJvUXNZSlYyNDJPY3MvV0h1WXdEUVlKS29aSWh2Y05BUUVMQlFBRApnZ0VCQUVYVU85dXBiTm1PNkQrUSt0aGRVc0FvLzRZZ0J2cUtrdHpXbXN3N1lmNHJERXN6M2ZRNk1hRUhmMk1KCjUwNE9Sa2J3d3g1RzQ4ZE5acGdXM21wc0t5a3N1dS82TUl3QkxiWXVoMHhuclpFTVh5dFlYNSt5M2IrREJQYlgKZ2R0dHVLMjBtdmFuWlJUcC9BakZpTVJlRXJlKzhkUFk4NWxDa3Fha0s5R0wrRExmWGYwZUkxcTFUZ3lYL0ZINwpUemE0MFZ2djRoSGhWRmRtb1lELy9pYUtQRDZVUzZCZ1hjRDZVcG1qN0M5VkxFNUZPbkgrMnROSzFwaTJuTW9tClp3a2ZnVDdHaHFqN3Y5Sll2REpPZXV1U215Y1dZby9NNFdpb3oyeFp4bjBhRTFuMnkrYVh1WTlKYnp5ZlhQbGYKbk1KT3ZKeXVrNGlFU3FVTWdUK1Z3aGpZZ0pFPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==","verification":{}}]}},"timeouts":{},"version":"2.2.0"},"networkd":{},"passwd":{},"storage":{},"systemd":{}}
END_OF_MASTER_IGNITION

// Ignition config for the compute machines. You should copy the contents of the worker.ign generated by the installer.
compute_ignition = <<END_OF_WORKER_IGNITION
{"ignition":{"config":{"append":[{"source":"https://api-int.openshift.bdlab.local:22623/config/worker","verification":{}}]},"security":{"tls":{"certificateAuthorities":[{"source":"data:text/plain;charset=utf-8;base64,LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURFRENDQWZpZ0F3SUJBZ0lJUDRtN1Y3WFJEK2d3RFFZSktvWklodmNOQVFFTEJRQXdKakVTTUJBR0ExVUUKQ3hNSmIzQmxibk5vYVdaME1SQXdEZ1lEVlFRREV3ZHliMjkwTFdOaE1CNFhEVEl3TURVeU56RTVOVE15TWxvWApEVE13TURVeU5URTVOVE15TWxvd0pqRVNNQkFHQTFVRUN4TUpiM0JsYm5Ob2FXWjBNUkF3RGdZRFZRUURFd2R5CmIyOTBMV05oTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF0cFpBUWhoUzFjMVcKZWI2S2ZKS3h5Q1NiZG05eXJuaTAyaFUvMGZLNGo1MGp0MzRib3kvUnRncjVBMU5yRkovYkgrNnFSSmxYM1BLaAorUk4wL0p2cHVYODhxenZCcFpiOXVxQnR3eUtyRENpMWpzWTRIanpSc1ZFdVo0UFdPb0dRT1pucHY0ZG9nUU1xCjNZYzBRb2pieW5ESjhlNTgwcHJFZXd3Zm9IV1FSMVRyVDZaS1E0NFJqNmE4eU9TbzUreldaYnhOWkdqSksyeGMKQkNtUEtVSEpFK2xPbUNFYThMeWJKRHR5VTdMQmFVMm9OU2hIb1NuOG5VeTBFdE1wVldXVGJOblhJYmM3WFR4ZwpjU2o2R2pheWRnWmdjcURveHJneEl3ZGVWczZjQ2dMRkdEMHBKRHZ1YXg1TkpMQU1oZjZJTzJBUDllTTV6ME9iCkt0UlhqZjc2eVFJREFRQUJvMEl3UURBT0JnTlZIUThCQWY4RUJBTUNBcVF3RHdZRFZSMFRBUUgvQkFVd0F3RUIKL3pBZEJnTlZIUTRFRmdRVVhPRlpNYVJjcWJvUXNZSlYyNDJPY3MvV0h1WXdEUVlKS29aSWh2Y05BUUVMQlFBRApnZ0VCQUVYVU85dXBiTm1PNkQrUSt0aGRVc0FvLzRZZ0J2cUtrdHpXbXN3N1lmNHJERXN6M2ZRNk1hRUhmMk1KCjUwNE9Sa2J3d3g1RzQ4ZE5acGdXM21wc0t5a3N1dS82TUl3QkxiWXVoMHhuclpFTVh5dFlYNSt5M2IrREJQYlgKZ2R0dHVLMjBtdmFuWlJUcC9BakZpTVJlRXJlKzhkUFk4NWxDa3Fha0s5R0wrRExmWGYwZUkxcTFUZ3lYL0ZINwpUemE0MFZ2djRoSGhWRmRtb1lELy9pYUtQRDZVUzZCZ1hjRDZVcG1qN0M5VkxFNUZPbkgrMnROSzFwaTJuTW9tClp3a2ZnVDdHaHFqN3Y5Sll2REpPZXV1U215Y1dZby9NNFdpb3oyeFp4bjBhRTFuMnkrYVh1WTlKYnp5ZlhQbGYKbk1KT3ZKeXVrNGlFU3FVTWdUK1Z3aGpZZ0pFPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==","verification":{}}]}},"timeouts":{},"version":"2.2.0"},"networkd":{},"passwd":{},"storage":{},"systemd":{}}
END_OF_WORKER_IGNITION


// Set ipam and ipam_token if you want to use the IPAM server to reserve IP
// addresses for the VMs.

// Address or hostname of the IPAM server from which to reserve IP addresses for the cluster machines.
//ipam = "139.178.89.254"

// Token to use to authenticate with the IPAM server.
//ipam_token = "TOKEN_FOR_THE_IPAM_SERVER"


// Set bootstrap_ip, control_plane_ip, and compute_ip if you want to use static
// IPs reserved someone else, rather than the IPAM server.

// The IP address to assign to the bootstrap VM.
bootstrap_ip = "10.6.202.42"

// The IP addresses to assign to the control plane VMs. The length of this list
// must match the value of control_plane_count.
control_plane_ips = ["10.6.202.37", "10.6.202.38", "10.6.202.39"]

// The IP addresses to assign to the compute VMs. The length of this list must
// match the value of compute_count.
compute_ips = ["10.6.202.40", "10.6.202.45"]

vm_network="DPG_CORP_NET_208"


